### ISSUE TITLE
Don't delete source directory if exists

### ISSUE THREAD

**Issue by amarts** [aravindavk/gluster-tester#1]
If one wants to run the tests in laptop, if we remove the source directory, it is not a good idea. We should not remove the directory if there is already changes in the repository.

**Comment by aravindavk** [comment]
I was facing an issue during checkout If I run the `gluster-tester` second time. It was checking out to some old commit. Now I am thinking about clone and rpm generation also inside a container so that Master VM/machine will not be spoiled. I will make the changes and push it by today.

**Comment by amarts** [comment]
Fixed by 9a5133f4903441e4341dc76a92074c90c6e964fc
